baseURL = 'https://antoinepoulin.com'
languageCode = 'en-us'
title = 'Antoine Poulin'
theme = 'terminal'
timeZone = "America/Toronto"

[menus]
  [[menus.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20
  [[menus.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 30
  [[menus.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 40
  [[menus.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 50

paginate = 10

[permalinks]
  blog = "/blog/:year/:month/:day/:title/"

[taxonomies]
  tag = "tags"
  author = "authors"

[indexes]
  tag = "tags"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    smartypants = true
    fractions = true
    superscript = true
    unsafe = true

[params]
    siteName = "Antoine Poulin"
    catchPhrase = "Backend Developer - Internal Tooling"
    [[params.social]]
      name = "github"
      url = "https://github.com/Dwarf1er"
      alt= "GitHub Profile"
    [[params.social]]
      name = "linkedin"
      url = "https://linkedin.com/in/antoine-poulin"
      alt= "LinkedIn Profile"
    [[params.social]]
      name = "email"
      url = "mailto:contact@antoinepoulin.com"
      alt= "Email Contact"
    [[params.projects]]
      title = "OpenLabel"
      description = "C# library for ZPL label applications that makes network printing, scaling, and templating easy."
      image = "/openlabel.png"
      repo = "https://github.com/Dwarf1er/openlabel"
      stars = "https://img.shields.io/github/stars/Dwarf1er/OpenLabel?style=for-the-badge&logo=github"
      demo = "https://nuget.org/packages/openlabel"
    [[params.projects]]
      title = "Environment Variable Explorer"
      description = "Environment Variable Explorer is a cross-platform tool for managing environment variables."
      image = "/environment-variable-explorer-logo.png"
      repo = "https://github.com/Dwarf1er/environment-variable-explorer"
      demo = ""

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
